/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TicketJava;
//header files

import java.awt.Component;
import java.util.Scanner; 
import java.util.Random;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.SimpleTimeZone;



/**
 *
 * @author Abinav Gowtham
 */
public class Ticket extends javax.swing.JFrame {

    /**
     * Creates new form Ticket
     */
    public Ticket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        firstclass = new javax.swing.JRadioButton();
        standard = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        single = new javax.swing.JRadioButton();
        returns = new javax.swing.JRadioButton();
        adultlabel = new javax.swing.JLabel();
        child = new javax.swing.JTextField();
        adult = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        seniorcitizen = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        source = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        destination = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        subtotal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        taxtotal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tax = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        exitbox = new javax.swing.JButton();
        economy = new javax.swing.JRadioButton();
        totals = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        adultno = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        childno = new javax.swing.JTextField();
        seniorcitizenno = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        from = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        route = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        classtype = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        journytype = new javax.swing.JTextField();
        dates = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        time = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        to = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        randomnumber = new javax.swing.JTextField();
        jInternalFrame1 = new javax.swing.JInternalFrame();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        Desktop.setBackground(new java.awt.Color(204, 204, 204));
        Desktop.setPreferredSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel26.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel26.setText("INDIAN SOUNTHERN RAILWAYS TICKETING SYSTEM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 1311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel26)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("CLASS:");

        firstclass.setBackground(new java.awt.Color(255, 255, 255));
        firstclass.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        firstclass.setText("FirstClass");
        firstclass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstclassActionPerformed(evt);
            }
        });

        standard.setBackground(new java.awt.Color(255, 255, 255));
        standard.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        standard.setText("Standard");
        standard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                standardActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("JOURNEY TYPE:");

        single.setBackground(new java.awt.Color(255, 255, 255));
        single.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        single.setText("Single");
        single.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singleActionPerformed(evt);
            }
        });

        returns.setBackground(new java.awt.Color(255, 255, 255));
        returns.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        returns.setText("Return");
        returns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnsActionPerformed(evt);
            }
        });

        adultlabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        adultlabel.setText("ADULT:");

        child.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        child.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        adult.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        adult.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("CHILDREN:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("SENIOR CITIZEN:");

        seniorcitizen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        seniorcitizen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("SOURCE:");

        source.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHENNAI CENTRAL" }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("DESTINATION:");

        destination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "....", "THIRUVOTRIYUR", "PONNERI", "GUMMIDIPOONDI", "SULLURPETA" }));

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("SUB TOTAL:");

        subtotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        subtotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("TAX:");

        taxtotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        taxtotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("TOTAL:");

        tax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tax, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                            .addComponent(taxtotal)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addComponent(subtotal, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(tax, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(taxtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jButton2.setBackground(new java.awt.Color(255, 204, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("RESET...");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        exitbox.setBackground(new java.awt.Color(255, 0, 51));
        exitbox.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        exitbox.setText("EXIT...");
        exitbox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        exitbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitboxActionPerformed(evt);
            }
        });

        economy.setBackground(new java.awt.Color(255, 255, 255));
        economy.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        economy.setText("Economy");
        economy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                economyActionPerformed(evt);
            }
        });

        totals.setBackground(new java.awt.Color(51, 255, 0));
        totals.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        totals.setText("TOTAL");
        totals.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        totals.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                totalsMouseClicked(evt);
            }
        });
        totals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(adultlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(adult, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                    .addComponent(child)
                                    .addComponent(seniorcitizen))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46)
                                        .addComponent(firstclass)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(standard))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(112, 112, 112)
                                        .addComponent(single, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 8, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(economy)
                                    .addComponent(returns, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(source, 0, 217, Short.MAX_VALUE)
                                    .addComponent(destination, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(totals, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(611, 611, 611)
                        .addComponent(exitbox, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(firstclass)
                            .addComponent(standard)
                            .addComponent(economy))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(single)
                                .addComponent(returns, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(adult, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(adultlabel))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(jLabel4))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(child)
                                        .addGap(2, 2, 2))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(source, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(destination, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seniorcitizen, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(totals, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(exitbox, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("ADULT");

        adultno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        adultno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("CHILD");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("ROUTE");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("SENIOR CITIZEN");

        childno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        childno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        childno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                childnoActionPerformed(evt);
            }
        });

        seniorcitizenno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        seniorcitizenno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        seniorcitizenno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seniorcitizennoActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("CLASS");

        from.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        from.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("JOURNEY TYPE");

        route.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        route.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        route.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                routeActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("FROM");

        classtype.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        classtype.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setText("PRICE");

        journytype.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        journytype.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        dates.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dates.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("DATE");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("TO");

        time.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        time.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("INSTRCTIONS:");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("1. Keep our luggages safe and dont put the trashes into the train.");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("2. Travelling on the top roof and footboard of the train is punishable.");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("3. Travelling without the ticket in train is punishable.");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("(including all taxes and retails)");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addComponent(jLabel24)
                .addGap(18, 18, 18)
                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                .addContainerGap())
        );

        to.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        to.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        price.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        price.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel30.setText("TIME");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("TICKET.NO");

        randomnumber.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        randomnumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        randomnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomnumberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(5, 5, 5)
                                    .addComponent(adultno, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(24, 24, 24)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(childno, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(seniorcitizenno, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(71, 71, 71)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(from, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel21)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(to, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(journytype, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dates, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGap(90, 90, 90)
                                            .addComponent(route, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(classtype, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jLabel3))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(randomnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(route, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(childno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                                    .addComponent(adultno, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(seniorcitizenno))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel15)
                                        .addComponent(classtype, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(journytype, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(to, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(dates, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel30))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel17)
                                    .addComponent(from, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21))))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(randomnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Desktop.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Desktop.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Desktop.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesktopLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DesktopLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(400, Short.MAX_VALUE))
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesktopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(384, Short.MAX_VALUE))
        );

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
single.setSelected(false);
returns.setSelected(false);
economy.setSelected(false);
standard.setSelected(false);
firstclass.setSelected(false);
child.setText("");
adult.setText(" ");
seniorcitizen.setText("");
subtotal.setText("");
tax.setText("");
taxtotal.setText("");
source.setSelectedIndex(0);
destination.setSelectedIndex(0);
journytype.setText("");
classtype.setText("");
route.setText("");
childno.setText("");
adultno.setText(" ");
seniorcitizenno.setText("");
dates.setText("");
time.setText("");
from.setText("");
to.setText("");
randomnumber.setText("");
price.setText("");


// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void seniorcitizennoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seniorcitizennoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seniorcitizennoActionPerformed

    private void childnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_childnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_childnoActionPerformed

    private void routeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_routeActionPerformed

    private void timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeActionPerformed

    private void standardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_standardActionPerformed
if(standard.isSelected())
{
economy.setSelected(false);
firstclass.setSelected(false);
}// TODO add your handling code here:
    }//GEN-LAST:event_standardActionPerformed

    private void economyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_economyActionPerformed
if(economy.isSelected())
{
standard.setSelected(false);
firstclass.setSelected(false);
}// TODO add your handling code here:
    }//GEN-LAST:event_economyActionPerformed

    private void firstclassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstclassActionPerformed
if(firstclass.isSelected())
{
standard.setSelected(false);
economy.setSelected(false);
}        // TODO add your handling code here:
    }//GEN-LAST:event_firstclassActionPerformed

    private void singleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singleActionPerformed
if(single.isSelected()) 
{
returns.setSelected(false);
}// TODO add your handling code here:
    }//GEN-LAST:event_singleActionPerformed

    private void returnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnsActionPerformed
if(returns.isSelected()) 
{
single.setSelected(false);
}        // TODO add your handling code here:
    }//GEN-LAST:event_returnsActionPerformed

    private void exitboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitboxActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_exitboxActionPerformed

    private void totalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalsActionPerformed
int a=Integer.parseInt(adult.getText());
adultno.setText(Integer.toString(a));
int b=Integer.parseInt(child.getText());
childno.setText(Integer.toString(b));
int c=Integer.parseInt(seniorcitizen.getText());
seniorcitizenno.setText(Integer.toString(c));
if(standard.isSelected())
    classtype.setText("Standard");
if(economy.isSelected())
    classtype.setText("Economy");
if(firstclass.isSelected())
    classtype.setText("FirstClass");
if(single.isSelected())
    journytype.setText("Single");
if(returns.isSelected())
    journytype.setText("Return");
from.setText(source.getSelectedItem().toString());
to.setText(destination.getSelectedItem().toString());
int numl;
String q1="";
numl=1000+(int)(Math.random()*4238);
q1+=numl+1000;
randomnumber.setText(q1);
route.setText("Any");
Calendar cal=Calendar.getInstance();
int month=cal.get(Calendar.MONTH);
int year=cal.get(Calendar.YEAR);
int day=cal.get(Calendar.DAY_OF_MONTH);
dates.setText(day+"/"+(month+1)+"/"+year);
int minutes=cal.get(Calendar.MINUTE);
int hour=cal.get(Calendar.HOUR_OF_DAY);
time.setText(hour+":"+minutes);
double taxs=5.59;
double k5=5;
double k10=7.5;
double k15=10;
double k20=12.5;
double k30=15;
double totalcost,eco=3,fc=5,std=1.5;
if((standard.isSelected())&&(single.isSelected())&&destination.getSelectedItem().equals("THIRUVOTRIYUR"))
{
    
    totalcost=((taxs+k5)+a)/100;
    String stax=String.format("Rs%.2f",+totalcost);
    tax.setText(stax);
    String totalsub=String.format("Rs%.2f",+(std*(a+b+c))+(k5*a+k5*b/2+c*k5/1.3));
    subtotal.setText(totalsub);
    String total=String.format("Rs%.2f",+((std*(a+b+c))+((k5*a+k5*b/2+c*k5/1.3))+totalcost));
    price.setText(total);
     taxtotal.setText(total);
    

}
else if((standard.isSelected())&&(returns.isSelected())&&destination.getSelectedItem().equals("THIRUVOTRIYUR"))
{
    totalcost=((taxs*k10)+a)/100*2;
    String stax=String.format("Rs%.2f",+totalcost);
    tax.setText(stax);
    String totalsub=String.format("Rs%.2f",+(std*(a+b+c)*2)+((k5*a+k5*b/2+c*k5/1.3)*2));
    subtotal.setText(totalsub);
    String total=String.format("Rs%.2f",+((std*(a+b+c)*2)+(((k5*a+k5*b/2+c*k5/1.3))+totalcost)*2));
    price.setText(total);
     taxtotal.setText(total);
}
else if((economy.isSelected())&&(single.isSelected())&&destination.getSelectedItem().equals("THIRUVOTRIYUR"))
{
    totalcost=((taxs+k5)*a)/100;
    String stax=String.format("Rs%.2f",+totalcost);
    tax.setText(stax);
    String totalsub=String.format("Rs%.2f",+(eco*(a+b+c))+(k5*a+k5*b/2+c*k5/1.3));
    subtotal.setText(totalsub);
    String total=String.format("Rs%.2f",+(eco*(a+b+c))+(k5*a+k5*b/2+c*k5/1.3)+totalcost);
    price.setText(total);
     taxtotal.setText(total);
}
else if((economy.isSelected())&&(returns.isSelected())&&destination.getSelectedItem().equals("THIRUVOTRIYUR"))
{
    totalcost=((taxs+k10)*a)/100*2;
    String stax=String.format("Rs%.2f",+totalcost);
    tax.setText(stax);
    String totalsub=String.format("Rs%.2f",+(eco*(a+b+c)*2)+((k5*a+k5*b/2+c*k5/1.3)*2));
    subtotal.setText(totalsub);
    String total=String.format("Rs%.2f",+(eco*(a+b+c)*2)+(((k5*a+k5*b/2+c*k5/1.3)+totalcost)*2));
    price.setText(total);
     taxtotal.setText(total);
}
else if((firstclass.isSelected())&&(single.isSelected())&&destination.getSelectedItem().equals("THIRUVOTRIYUR"))
{
    totalcost=((taxs+k5)*a)/100*2;
    String stax=String.format("Rs%.2f",+totalcost);
    tax.setText(stax);
    String totalsub=String.format("Rs%.2f",+(fc*(a+b+c))+(k5*a+k5*b/2+c*k5/1.3));
    subtotal.setText(totalsub);
    String total=String.format("Rs%.2f",+(fc*(a+b+c))+((k5*a+k5*b/2+c*k5/1.3)+totalcost));
    price.setText(total);
     taxtotal.setText(total);
}
else if((firstclass.isSelected())&&(returns.isSelected())&&destination.getSelectedItem().equals("THIRUVOTRIYUR"))
{
    totalcost=((taxs+k10)*a)/100*2;
    String stax=String.format("Rs%.2f",+totalcost);
    tax.setText(stax);
    String totalsub=String.format("Rs%.2f",+(fc*(a+b+c))+((k5*a+k5*b/2+c*k5/1.3)*2));
    subtotal.setText(totalsub);
    String total=String.format("Rs%.2f",+(fc*(a+b+c))+((k5*a+k5*b/2+c*k5/1.3)*2));
    price.setText(total);
     taxtotal.setText(total);
}
else if((standard.isSelected())&&(single.isSelected())&&destination.getSelectedItem().equals("PONNERI"))
{
    totalcost=((taxs*10)*a)/100;
    String stax=String.format("Rs%.2f",+totalcost);
    tax.setText(stax);
    String totalsub=String.format("Rs%.2f",+(std*(a+b+c))+(k10*a+k10*b/2+c*k10/1.3));
    subtotal.setText(totalsub);
    String total=String.format("Rs%.2f",+((std*(a+b+c))+((k10*a+k10*b/2+c*k10/1.3))+totalcost));
    price.setText(total);
     taxtotal.setText(total);
}
else if((standard.isSelected())&&(returns.isSelected())&&destination.getSelectedItem().equals("PONNERI"))
{
    totalcost=((taxs*k15)*a)/100*2;
    String stax=String.format("Rs%.2f",+totalcost);
    tax.setText(stax);
    String totalsub=String.format("Rs%.2f",+(std*(a+b+c)*2)+((k10*a+k10*b/2+c*k10/1.3)*2));
    subtotal.setText(totalsub);
    String total=String.format("Rs%.2f",+((std*(a+b+c)*2)+(((k10*a+k10*b/2+c*k10/1.3))+totalcost)*2));
    price.setText(total);
     taxtotal.setText(total);
}
else if((economy.isSelected())&&(single.isSelected())&&destination.getSelectedItem().equals("PONNERI"))
{
    totalcost=((taxs*k10)*a)/100;
    String stax=String.format("Rs%.2f",+totalcost);
    tax.setText(stax);
    String totalsub=String.format("Rs%.2f",+(eco*(a+b+c))+(k10*a+k10*b/2+c*k10/1.3));
    subtotal.setText(totalsub);
    String total=String.format("Rs%.2f",+(eco*(a+b+c))+(k10*a+k10*b/2+c*k10/1.3)+totalcost);
    price.setText(total);
     taxtotal.setText(total);
}
else if((economy.isSelected())&&(returns.isSelected())&&destination.getSelectedItem().equals("PONNERI"))
{
    totalcost=((taxs*k15)*a)/100;
    String stax=String.format("Rs%.2f",+totalcost);
    tax.setText(stax);
    String totalsub=String.format("Rs%.2f",+(eco*(a+b+c)*2)+((k10*a+k10*b/2+c*k10/1.3)*2));
    subtotal.setText(totalsub);
    String total=String.format("Rs%.2f",+(eco*(a+b+c)*2)+((k10*a+k10*b/2+c*k10/1.3)+totalcost)*2);
    price.setText(total);
     taxtotal.setText(total);
}
else if((firstclass.isSelected())&&(single.isSelected())&&destination.getSelectedItem().equals("PONNERI"))
{
    totalcost=((taxs*k10)*a)/100;
    String stax=String.format("Rs%.2f",+totalcost);
    tax.setText(stax);
    String totalsub=String.format("Rs%.2f",+(fc*(a+b+c))+(k10*a+k10*b/2+c*k10/1.3));
    subtotal.setText(totalsub);
    String total=String.format("Rs%.2f",+(fc*(a+b+c))+((k10*a+k10*b/2+c*k10/1.3)+totalcost));
    price.setText(total);
     taxtotal.setText(total);
}
else if((firstclass.isSelected())&&(returns.isSelected())&&destination.getSelectedItem().equals("PONNERI"))
{
    totalcost=((taxs*k15)*a)/100*2;
    String stax=String.format("Rs%.2f",+totalcost);
    tax.setText(stax);
    String totalsub=String.format("Rs%.2f",+(fc*(a+b+c))+((k10*a+k10*b/2+c*k10/1.3)*2));
    subtotal.setText(totalsub);
    String total=String.format("Rs%.2f",+(fc*(a+b+c))+((k10*a+k10*b/2+c*k10/1.3+totalcost)*2));
    price.setText(total);
     taxtotal.setText(total);
}
else if((standard.isSelected())&&(single.isSelected())&&destination.getSelectedItem().equals("GUMMIDIPOONDI"))
{
    totalcost=((taxs*k15)*a)/100;
    String stax=String.format("Rs%.2f",+totalcost);
    tax.setText(stax);
     String totalsub=String.format("Rs%.2f",+(std*(a+b+c))+(k15*a+k15*b/2+c*k15/1.3));
    subtotal.setText(totalsub);
    String total=String.format("Rs%.2f",+((std*(a+b+c))+((k15*a+k15*b/2+c*k15/1.3))+totalcost));
    price.setText(total);
     taxtotal.setText(total);
}
else if((standard.isSelected())&&(returns.isSelected())&&destination.getSelectedItem().equals("GUMMIDIPOONDI"))
{
    totalcost=((taxs*k20)*a)/100*2;
    String stax=String.format("Rs%.2f",+totalcost);
    tax.setText(stax);
    String totalsub=String.format("Rs%.2f",+(std*(a+b+c)*2)+((k15*a+k15*b/2+c*k15/1.3)*2));
    subtotal.setText(totalsub);
    String total=String.format("Rs%.2f",+((std*(a+b+c)*2)+(((k15*a+k15*b/2+c*k15/1.3))+totalcost)*2));
    price.setText(total);
     taxtotal.setText(total);
}
else if((economy.isSelected())&&(single.isSelected())&&destination.getSelectedItem().equals("GUMMIDIPOONDI"))
{
    totalcost=((taxs*k15)*a)/100*2;
    String stax=String.format("Rs%.2f",+totalcost);
    tax.setText(stax);
    String totalsub=String.format("Rs%.2f",+(eco*(a+b+c))+(k15*a+k15*b/2+c*k15/1.3));
    subtotal.setText(totalsub);
    String total=String.format("Rs%.2f",+(eco*(a+b+c))+(k15*a+k15*b/2+c*k15/1.3)+totalcost);
    price.setText(total);
     taxtotal.setText(total);
}
else if((economy.isSelected())&&(returns.isSelected())&&destination.getSelectedItem().equals("GUMMIDIPOONDI"))
{
    totalcost=((taxs*k20)*a)/100*2;
    String stax=String.format("Rs%.2f",+totalcost);
    tax.setText(stax);
    String totalsub=String.format("Rs%.2f",+(eco*(a+b+c)*2)+((k15*a+k15*b/2+c*k15/1.3)*2));
    subtotal.setText(totalsub);
    String total=String.format("Rs%.2f",+(eco*(a+b+c)*2)+((k15*a+k15*b/2+c*k15/1.3)+totalcost)*2);
    price.setText(total);
     taxtotal.setText(total);
}
else if((firstclass.isSelected())&&(single.isSelected())&&destination.getSelectedItem().equals("GUMMIDIPOONDI"))
{
    totalcost=((taxs*k15)*a)/100;
    String stax=String.format("Rs%.2f",+totalcost);
    tax.setText(stax);
    String totalsub=String.format("Rs%.2f",+(fc*(a+b+c))+(k15*a+k15*b/2+c*k15/1.3));
    subtotal.setText(totalsub);
    String total=String.format("Rs%.2f",+(fc*(a+b+c))+((k15*a+k15*b/2+c*k15/1.3)+totalcost));
    price.setText(total);
     taxtotal.setText(total);
}
else if((firstclass.isSelected())&&(returns.isSelected())&&destination.getSelectedItem().equals("GUMMIDIPOONDI"))
{
    totalcost=((taxs*k20)*a)/100*2;
    String stax=String.format("Rs%.2f",+totalcost);
    tax.setText(stax);
   String totalsub=String.format("Rs%.2f",+(fc*(a+b+c))+((k10*a+k10*b/2+c*k10/1.3)*2));
    subtotal.setText(totalsub);
    String total=String.format("Rs%.2f",+(fc*(a+b+c))+((k10*a+k10*b/2+c*k10/1.3+totalcost)*2));
    price.setText(total);
     taxtotal.setText(total);
}
else if((standard.isSelected())&&(single.isSelected())&&destination.getSelectedItem().equals("SULLURPETA"))
{
    totalcost=((taxs*k20)*a)/100;
    String stax=String.format("Rs%.2f",+totalcost);
    tax.setText(stax);
    
     String totalsub=String.format("Rs%.2f",+(std*(a+b+c))+(k20*a+k20*b/2+c*k20/1.3));
    subtotal.setText(totalsub);
    String total=String.format("Rs%.2f",+((std*(a+b+c))+((k20*a+k20*b/2+c*k20/1.3))+totalcost));
    price.setText(total);
     taxtotal.setText(total);
}
else if((standard.isSelected())&&(returns.isSelected())&&destination.getSelectedItem().equals("SULLURPETA"))
{
    totalcost=((taxs*k30)*a)/100*2;
    String stax=String.format("Rs%.2f",+totalcost);
    tax.setText(stax);
   String totalsub=String.format("Rs%.2f",+(std*(a+b+c)*2)+((k20*a+k20*b/2+c*k20/1.3)*2));
    subtotal.setText(totalsub);
    String total=String.format("Rs%.2f",+((std*(a+b+c)*2)+(((k20*a+k20*b/2+c*k20/1.3))+totalcost)*2));
    price.setText(total);
     taxtotal.setText(total);
}
else if((economy.isSelected())&&(single.isSelected())&&destination.getSelectedItem().equals("SULLURPETA"))
{
    totalcost=((taxs*k20)*a)/100;
    String stax=String.format("Rs%.2f",+totalcost);
    tax.setText(stax);
     String totalsub=String.format("Rs%.2f",+(eco*(a+b+c))+(k20*a+k20*b/2+c*k20/1.3));
    subtotal.setText(totalsub);
    String total=String.format("Rs%.2f",+(eco*(a+b+c))+(k20*a+k20*b/2+c*k20/1.3)+totalcost);
    price.setText(total);
     taxtotal.setText(total);
}
else if((economy.isSelected())&&(returns.isSelected())&&destination.getSelectedItem().equals("SULLURPETA"))
{
    totalcost=((taxs*k30)*a)/100*2;
    String stax=String.format("Rs%.2f",+totalcost);
    tax.setText(stax);
    String totalsub=String.format("Rs%.2f",+(eco*(a+b+c)*2)+((k20*a+k20*b/2+c*k20/1.3)*2));
    subtotal.setText(totalsub);
    String total=String.format("Rs%.2f",+(eco*(a+b+c)*2)+((k20*a+k20*b/2+c*k20/1.3)+totalcost)*2);
    price.setText(total);
     taxtotal.setText(total);
}
else if((firstclass.isSelected())&&(single.isSelected())&&destination.getSelectedItem().equals("SULLURPETA"))
{
    totalcost=((taxs*k20)*a)/100;
    String stax=String.format("Rs%.2f",+totalcost);
    tax.setText(stax);
    String totalsub=String.format("Rs%.2f",+(fc*(a+b+c))+(k20*a+k20*b/2+c*k20/1.3));
    subtotal.setText(totalsub);
    String total=String.format("Rs%.2f",+(fc*(a+b+c))+((k20*a+k20*b/2+c*k20/1.3)+totalcost));
    price.setText(total);
     taxtotal.setText(total);
}
else if((firstclass.isSelected())&&(returns.isSelected())&&destination.getSelectedItem().equals("SULLURPETA"))
{
    totalcost=((taxs*k30)*a)/100*2;
    String stax=String.format("Rs%.2f",+totalcost);
    tax.setText(stax);
     String totalsub=String.format("Rs%.2f",+(fc*(a+b+c))+((k20*a+k20*b/2+c*k20/1.3)*2));
    subtotal.setText(totalsub);
    String total=String.format("Rs%.2f",+(fc*(a+b+c))+((k20*a+k20*b/2+c*k20/1.3+totalcost)*2));
    price.setText(total);
     taxtotal.setText(total);
}

// TODO add your handling code here:
    }//GEN-LAST:event_totalsActionPerformed

    private void randomnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_randomnumberActionPerformed

    private void totalsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_totalsMouseClicked
       // TODO add your handling code here:
    }//GEN-LAST:event_totalsMouseClicked

    private void taxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ticket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JTextField adult;
    private javax.swing.JLabel adultlabel;
    private javax.swing.JTextField adultno;
    private javax.swing.JTextField child;
    private javax.swing.JTextField childno;
    private javax.swing.JTextField classtype;
    private javax.swing.JTextField dates;
    private javax.swing.JComboBox<String> destination;
    private javax.swing.JRadioButton economy;
    private javax.swing.JButton exitbox;
    private javax.swing.JRadioButton firstclass;
    private javax.swing.JTextField from;
    private javax.swing.JButton jButton2;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField journytype;
    private javax.swing.JTextField price;
    private javax.swing.JTextField randomnumber;
    private javax.swing.JRadioButton returns;
    private javax.swing.JTextField route;
    private javax.swing.JTextField seniorcitizen;
    private javax.swing.JTextField seniorcitizenno;
    private javax.swing.JRadioButton single;
    private javax.swing.JComboBox<String> source;
    private javax.swing.JRadioButton standard;
    private javax.swing.JTextField subtotal;
    private javax.swing.JTextField tax;
    private javax.swing.JTextField taxtotal;
    private javax.swing.JTextField time;
    private javax.swing.JTextField to;
    private javax.swing.JButton totals;
    // End of variables declaration//GEN-END:variables
}
